// TypeScript wrapper for catrender-wasm bindings. Lazy-inits on first use.
// pkg/ generated by:
//   cd extensions/catrender-wasm && wasm-pack build --target web \
//     --out-dir ../../src/lib/structure/catrender/catrender-wasm-pkg

import { browser } from '$app/environment'

type WasmInitInput =
  | string | URL | Request | Response | BufferSource
  | WebAssembly.Module | { module_or_path: WasmInitInput }

type CatrenderWasmModule = {
  default: (input: WasmInitInput) => Promise<void>
  render: (input_json: string) => string
}

let _module: CatrenderWasmModule | null = null
let _init_promise: Promise<CatrenderWasmModule> | null = null

async function ensure_ready(): Promise<CatrenderWasmModule> {
  if (!browser) throw new Error(`catrender-wasm is browser-only`)
  if (_module) return _module
  if (_init_promise) return _init_promise

  _init_promise = (async () => {
    // @ts-ignore — generated WASM package
    const mod = (await import(/* @vite-ignore */ `./catrender-wasm-pkg/catrender_wasm.js`)) as unknown as CatrenderWasmModule
    const preloaded = (globalThis as unknown as {
      __catgo_catrender_wasm?: ArrayBuffer | Uint8Array
    }).__catgo_catrender_wasm
    if (preloaded) {
      await mod.default(preloaded)
    } else {
      const wasm_url_module = await import(
        /* @vite-ignore */ `./catrender-wasm-pkg/catrender_wasm_bg.wasm?url`
      )
      await mod.default({ module_or_path: wasm_url_module.default as string })
    }
    _module = mod
    return mod
  })()
  return _init_promise
}

/** Render molecular SVG. Runs entirely in-browser via WebAssembly. */
export async function render_svg(input_json: string): Promise<string> {
  const mod = await ensure_ready()
  return mod.render(input_json)
}
